[build]
  base = "frontend/"
  publish = "out"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  BACKEND_URL = "https://signal-watcher-1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200